name: Test
on:
  workflow_dispatch:
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: joaomiguelnobre/myFirstAction@v1/hello-world-docker-action
        with:
          who-to-greet: '@octocat'
